// Frontend/Hands_On_6/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {
  const enrolledCount = useSelector(
    (state) => state.enrollment.enrolledCourses.length
  );

  return (
    <header className="header">
      <div className="logo">
        Student Portal
      </div>

      <nav>
        <Link to="/">Home</Link>
        <Link to="/courses">Courses</Link>
        <Link to="/profile">Profile</Link>
      </nav>

      <div className="count">
        Enrolled: {enrolledCount}
      </div>
    </header>
  );
}

export default Header;

// Frontend/Hands_On_8/src/components/Header.vue
<template>
  <header class="header">
    <h1>Student Portal</h1>

    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">
        Profile ({{ store.enrolledCourses.length }})
      </RouterLink>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
.header {
  background: #2563eb;
  color: white;
  padding: 16px 30px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

nav {
  display: flex;
  gap: 20px;
}

a {
  color: white;
  text-decoration: none;
  font-weight: bold;
}

.router-link-active {
  border-bottom: 2px solid white;
}
</style>
